# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/i2s_receiver_0/i2s_receiver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==i2s_receiver_0 || ORIG_REF_NAME==i2s_receiver_0} -quiet] -quiet
