# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DSD/Labos_2022/DSD-project/code/DSD-Audio-with-microblaze/DSD-Audio-with-microblaze.srcs/sources_1/bd/microblaze_i2s/ip/microblaze_i2s_i2s_transmitter_0_0/microblaze_i2s_i2s_transmitter_0_0.xci
# IP: The module: 'microblaze_i2s_i2s_transmitter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DSD/Labos_2022/DSD-project/code/DSD-Audio-with-microblaze/DSD-Audio-with-microblaze.srcs/sources_1/bd/microblaze_i2s/ip/microblaze_i2s_i2s_transmitter_0_0/microblaze_i2s_i2s_transmitter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_i2s_i2s_transmitter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/DSD/Labos_2022/DSD-project/code/DSD-Audio-with-microblaze/DSD-Audio-with-microblaze.srcs/sources_1/bd/microblaze_i2s/ip/microblaze_i2s_i2s_transmitter_0_0/microblaze_i2s_i2s_transmitter_0_0.xci
# IP: The module: 'microblaze_i2s_i2s_transmitter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DSD/Labos_2022/DSD-project/code/DSD-Audio-with-microblaze/DSD-Audio-with-microblaze.srcs/sources_1/bd/microblaze_i2s/ip/microblaze_i2s_i2s_transmitter_0_0/microblaze_i2s_i2s_transmitter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_i2s_i2s_transmitter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
