# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DSD/Labos_2022/DSD-project/code/i2s_receiver_0_ex/i2s_receiver_0_ex.srcs/sources_1/ip/i2s_transmitter_1/i2s_transmitter_1.xci
# IP: The module: 'i2s_transmitter_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DSD/Labos_2022/DSD-project/code/i2s_receiver_0_ex/i2s_receiver_0_ex.srcs/sources_1/ip/i2s_transmitter_1/i2s_transmitter_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'i2s_transmitter_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/DSD/Labos_2022/DSD-project/code/i2s_receiver_0_ex/i2s_receiver_0_ex.srcs/sources_1/ip/i2s_transmitter_1/i2s_transmitter_1.xci
# IP: The module: 'i2s_transmitter_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DSD/Labos_2022/DSD-project/code/i2s_receiver_0_ex/i2s_receiver_0_ex.srcs/sources_1/ip/i2s_transmitter_1/i2s_transmitter_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'i2s_transmitter_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
