# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microblaze_i2s/microblaze_i2s.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s || ORIG_REF_NAME==microblaze_i2s} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_microblaze_0_0/microblaze_i2s_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_microblaze_0_0 || ORIG_REF_NAME==microblaze_i2s_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_clk_wiz_0_0/microblaze_i2s_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_clk_wiz_0_0 || ORIG_REF_NAME==microblaze_i2s_clk_wiz_0_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_i2s_receiver_0_0/microblaze_i2s_i2s_receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_i2s_receiver_0_0 || ORIG_REF_NAME==microblaze_i2s_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_i2s_transmitter_0_0/microblaze_i2s_i2s_transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_i2s_transmitter_0_0 || ORIG_REF_NAME==microblaze_i2s_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_axi_uartlite_0_0/microblaze_i2s_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze_i2s_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_axi_timer_0_0/microblaze_i2s_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_axi_timer_0_0 || ORIG_REF_NAME==microblaze_i2s_axi_timer_0_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_dlmb_v10_0/microblaze_i2s_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_dlmb_v10_0 || ORIG_REF_NAME==microblaze_i2s_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_ilmb_v10_0/microblaze_i2s_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_ilmb_v10_0 || ORIG_REF_NAME==microblaze_i2s_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_dlmb_bram_if_cntlr_0/microblaze_i2s_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_i2s_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_ilmb_bram_if_cntlr_0/microblaze_i2s_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze_i2s_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_lmb_bram_0/microblaze_i2s_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_lmb_bram_0 || ORIG_REF_NAME==microblaze_i2s_lmb_bram_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_mdm_1_0/microblaze_i2s_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_mdm_1_0 || ORIG_REF_NAME==microblaze_i2s_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_rst_clk_wiz_0_100M_0/microblaze_i2s_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==microblaze_i2s_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_xbar_0/microblaze_i2s_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_xbar_0 || ORIG_REF_NAME==microblaze_i2s_xbar_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_microblaze_0_axi_periph_0/microblaze_i2s_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze_i2s_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze_i2s/ip/microblaze_i2s_axi_timer_1_0/microblaze_i2s_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_i2s_axi_timer_1_0 || ORIG_REF_NAME==microblaze_i2s_axi_timer_1_0} -quiet] -quiet

# XDC: bd/microblaze_i2s/microblaze_i2s_ooc.xdc
